### ISSUE TITLE
mysql password - interrupt flow in script

### ISSUE THREAD

**Issue by voyo** [Appdynamics/support_report#16]
If mysql password is not present, script will wait for user to provide password interactively.
This is wrong, the assumption is that tool by default is non-interactive, and this behavior can be changed only by some option.
The support_report, later on, should be runnable by controller java process (by UI engine), and should not interrupt its flow or crash for no reason.

**Comment by psrpardhasaradhi** [comment]
There is -P switch. Better options I believe are being explored in #17

**Comment by voyo** [comment]
-P is allowing to provide password from command line, but by default (without any cmd line options) script is interrupting its flow and is waiting for user input.
For now - I like it, because when we are "beta testing" tool with customers it will somehow force (or encourage) the customer to provide mysql password and gives us more data in support report artifact.

But, IMHO the final version of the tool - should not interrupt its flow, and by default should not ask about anything. Just print a warning message, saying that something is not working/is not available etc. like when running as user not as root.
And yes, definitely we need to work on #17

**Comment by voyo** [comment]
solved by introducing timeout waiting for user input in get_mysql_password()
