### ISSUE TITLE
collect information about controller version

### ISSUE THREAD

**Issue by voyo** [Appdynamics/support_report#20]
I dont see anything like that available in database, or any other flat file.
Is it safe to get version number from some file name , like this
/appdynamics/platform/product/controller/appserver/glassfish/domains/domain1/applications/controller/lib/connector-api-4.5.12.2228.jar

thus controller version = 4.5.12.2228

but is it safe ? which file to use ? In my sandbox I see some files there referring to different version...

**Comment by voyo** [comment]
cat platform/product/controller/README.txt

Version 4.5.17.1
Build 4.5.17.2807

**Comment by cmayer68** [comment]
i always do this:

select value from global_configuration where name = 'schema.version';

--curt

On Thu, Feb 27, 2020 at 8:18 AM Voyo <notifications@github.com> wrote:

> cat platform/product/controller/README.txt
>
> Version 4.5.17.1
> Build 4.5.17.2807
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Appdynamics_support-5Freport_issues_20-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DADZV4TBA3Y4JGQM5QGEE7NLRE7RVDA5CNFSM4J2AX3XKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOENE6KYA-23issuecomment-2D592045408&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=iK027kav-WSQRdLMFPRnNzyuGldmtUkaiu4xYcMj0xI&s=zMCGRrB-IqxhVUTdHJcydOpODBM0TuOExGyoliUJO7Y&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ADZV4THHWOJJ2TN5NN4SAZDRE7RVDANCNFSM4J2AX3XA&d=DwMCaQ&c=3_5eq9zYXWRS8ywqccmjfTRKM8mRLoQp6HBg1Tdb_Pc&r=nsJ1Vt4kkj1MF7fPuYx_OHpUcucCi7WPVJJQ5IIS6oA&m=iK027kav-WSQRdLMFPRnNzyuGldmtUkaiu4xYcMj0xI&s=elTiTdDgQapDPq0L_00_3ubkfYYhF4PLXy8gilK5Zto&e=>
> .
>


-- 
*Curt Mayer* | Senior Architect, Customer Success
Office 707.540.3441 | Mobile 707.540.3441
<http://appdynamics.com/>
Watch  <http://appdynamics.wistia.com/medias/56gnkuk6mv>our Video | Try
<https://portal.appdynamics.com/account/signup/signupForm>our FREE Trial |
Twitter  <http://www.twitter.com/appdynamics>| Facebook
<http://www.facebook.com/pages/AppDynamics/193264136815?ref=nf>|
appdynamics.com <http://www.appdynamics.com/>

**Comment by plizonczyk** [comment]
Well yes, but the readme approach doesn't require mysql (root) pass.

**Comment by voyo** [comment]
schema.version is already collected, it is present in 34-controller-queries.txt  report (*if* user will provide mysql pass).
I can imagine that for some reason (broken upgrade ?) schema version can be different than controller version itself. 
Beside of this, best would be to have something like MD5 sum of all bin files, but thats another thing and I will address it somewhere else ;)

For now, both information will be collected  - schema.version and output from this README.txt
For easy to use and quick compare I will provide both of these in the same file

**Comment by psrpardhasaradhi** [comment]
/controller/rest/serverstatus API gets the implementation version from this file and shcema version from DB.

<controller_home>/appserver/glassfish/domains/domain1/applications/controller/META-INF/MANIFEST.MF

**Comment by voyo** [comment]
implemented 39-controller-info file, with all possible information collected.
(README, MANIFEST, API call, DB schema). Can be useful to compare with upgrade fail scenario.
