### ISSUE TITLE
ran: missing oddments

### ISSUE THREAD

**Issue by rnav1234** [Appdynamics/support_report#25]
From a brief review please address:
- 32-install-user-limits.txt has no ulimit -a output
- free -g output missing
- offer to split output into 10 megabyte chunks to fit with Zendesk limits
- openfiles listing 1.2 GB on my test machine <-- no real need for most queries

**Comment by voyo** [comment]
- ulimit for appd user (so java and mysql processes) is reported in 30-javainfo and 31-mysqlinfo files)
- free information is present in 37-meminfo
- split output to chunk files - we can consider this, please open separate issue, however I'm not convinced - I'd like to keep it simple for end user, not force them to download/upload multiple files. and there are other alternatives (dropzone)
- openfiles - disabled by default. will be collected if '-f' option added
