### ISSUE TITLE
Include sosreport

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/support_report#32]
Collect the *.tar.gz file from running the following command.
 Ignore if sosreport is not installed but do not fail.

`sosreport --batch`

**Comment by voyo** [comment]
what it have more than is available already in just support report ? (what is useful for us to troubleshooting).
support_report is designed to be superior tool over ie. sosreport, which is also rarely available on non-redhat servers.

**Comment by voyo** [comment]
If you think we need some functionality from sosreport - please create a separate issue to implement this.
