### ISSUE TITLE
possibility to encrypt output artefact

### ISSUE THREAD

**Issue by voyo** [Appdynamics/support_report#33]

**Comment by voyo** [comment]
By default, there are no hard requirements on the server to provide a tool which can encrypt anything.
There are some options, but nothing is obligatory - thus we don't have a guarantee to have something that will be always available.
The most reasonable and fastest way would be to use openssl , there is the biggest chance it will be available on the customer's server, also it will be easy to support engineers to decrypt it later.

Another tempting alternative is to write file encryption directly on bash, what will not have any dependencies...

**Comment by plizonczyk** [comment]
> Another tempting alternative is to write file encryption directly on bash, what will not have any dependencies...

ouch

**Comment by voyo** [comment]
I implemented it with openssl, encryption is optional, enables with -e argument, then asks for password (key) for encryption. I decided to use aes-256-cbc , what I think is considered as safe enough and not easy to bruteforce cracking attempt.
